Fix dependency checking

diff --git a/gmi b/gmi
--- a/gmi
+++ b/gmi
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
 # Wrap gmiget to provide defaults for retrieving gemini
-# pages
+# pages.
 
 for dep in gmiget gmifmt; do
-    command -v "$dep" >/dev/null || echo "Missing '$dep'"
+  command -v "${dep}" >/dev/null 2>&1 || {
+    echo >&2 "Missing binary '${dep}'"
+    exit 1
+  }
 done
 
 gmiget $1 | gmifmt -m 2 | less -EXFrM
